### ISSUE TITLE
Functions graph tab doesn't show up

### ISSUE THREAD

**Issue by pjgsk** [microsoft/DurableFunctionsMonitor#100]
The tab doesn't show up at all in monitor. 
I know all is installed as required cause I can visualize the functions using Command Palette > Visualize Functions as a Graph defining location on disk.
What am I doing wrong?

**Comment by scale-tone** [comment]
Hi @pjgsk , DfMon VsCode extension shows a Function Graph of the _currently open project_ (provided that this project is an Azure Functions project, aka that it contains `host.json` file).
So all you need to do is to open your sources in VsCode.

**Comment by scale-tone** [comment]
Does that answer your question, @pjgsk ?

**Comment by scale-tone** [comment]
Hope it helps. Pls, open another issue, if any further questions.
