### ISSUE TITLE
Standalone: Cannot see task details when Task Hub name is 'orchestrations'

### ISSUE THREAD

**Issue by rsirny** [microsoft/DurableFunctionsMonitor#105]
It seems that there is some mix-up when fetching `js` and `cs` resources for details of tasks from Task Hub that is named `orchestrations` (I have other task hub called local which works fine). See attached screenshots for details.
![orchestrations-main](https://user-images.githubusercontent.com/13479723/233668037-b7f1f60b-b55e-4ba2-9c74-b363a5863236.png)
![orchestrations-detail](https://user-images.githubusercontent.com/13479723/233668053-977385bc-00c1-4784-a707-2d1fc2b7d370.png)
![orchestrations-detail2](https://user-images.githubusercontent.com/13479723/233668088-8075a35e-0371-4b38-8886-5053c1f0ac93.png)

**Comment by rsirny** [comment]
I am not sure if this will be accepted as bug, or if there is something wrong with my setup, but it seems that task hub name cannot contain characters like `_` or `-`.  This could be used in API route so that there is no collision with task hub names.

**Comment by scale-tone** [comment]
Fixed in v6.2.1, re-pushed under [6.2](https://hub.docker.com/layers/scaletone/durablefunctionsmonitor/6.2/images/sha256-dd73833e5a04a23fcfd64b5e0fe809940d7f6bfdf028d6481309353dffaceab0?context=explore) tag. Pls, validate.
