### ISSUE TITLE
Standalone, client-directed auth: failing to navigate to an orchestration details page

### ISSUE THREAD

**Issue by rsirny** [microsoft/DurableFunctionsMonitor#106]
I am using standalone deployment in Kubernetes with authentication enabled (my K8s objects were provided for [#102 ](https://github.com/microsoft/DurableFunctionsMonitor/issues/102)). When I click on the `instance id`, a new tab opens, but then I get redirected to Task Hub selection view. The issue occurs only in Chrome (`112.0.5615.138 (Official Build) (64-bit)`), Firefox and Microsoft Edge are working ok.

Here is the task overview with instance ids of various tasks
![task overview](https://user-images.githubusercontent.com/13479723/233851007-3e97b1da-fa2e-411a-abf9-cdede569c560.png)

This is how it looks like after clicking one of the instance ids to view details.
![task details with network](https://user-images.githubusercontent.com/13479723/233851008-e40d1cc1-c74a-4bf1-aebc-a8473d92333b.png)

![task details with console](https://user-images.githubusercontent.com/13479723/233851014-cbdfe22b-fb90-4d71-86bd-484b12a6a61c.png)

**Comment by scale-tone** [comment]
Hi @rsirny , thanks for reporting this!

I was able to repro, and [here is the fix](https://github.com/microsoft/DurableFunctionsMonitor/pull/107). 
Also pushed that branch as [scaletone/durablefunctionsmonitor:experimental-fix-for-106](https://hub.docker.com/layers/scaletone/durablefunctionsmonitor/experimental-fix-for-106/images/sha256-9838f7173b3e611d47ffbde8a5c9681892b40d206018f9a9bdf31df0cf0bf6cf?context=explore).

Can you please try that image and confirm that it resolves the issue?

**Comment by rsirny** [comment]
Thanks! It's working now in Chrome. I also tested Edge and Firefox to make sure the fix did not break anything and it is working as well.

**Comment by rsirny** [comment]
@scale-tone will there be a new docker image with the fix at some point?

**Comment by scale-tone** [comment]
Fixed in v6.2.1, re-pushed under [6.2](https://hub.docker.com/layers/scaletone/durablefunctionsmonitor/6.2/images/sha256-dd73833e5a04a23fcfd64b5e0fe809940d7f6bfdf028d6481309353dffaceab0?context=explore) tag. Pls, validate.

**Comment by scale-tone** [comment]
> Would it be possible to have docker images with patch part of the version as well? 

OK, pushed as [6.2.1](https://hub.docker.com/layers/scaletone/durablefunctionsmonitor/6.2.1/images/sha256-b4524a1174be49e5493dce4ed792846c572a2e4db4c911b92fa830f0dfa7881e?context=explore).
