### ISSUE TITLE
The data type of "aadClientId" is not converting to string

### ISSUE THREAD

**Issue by Nishanth123456789ab** [microsoft/DurableFunctionsMonitor#110]
Hi,
I am deploying "arm_template.json" file using terraform. So, for this, I am using "azurerm_resource_group_template_deployment" resource. But, when I deployed, I am getting the below error
Error: validating Template Deployment "Azure-deploy" (Resource Group "va7-int-rg_orchestration-acpquerypos-1"): requesting validating: resources.DeploymentsClient#Validate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidRequestContent" Message="The request content was invalid and could not be deserialized: 'Error converting value \"******-********\" to type 'Azure.Deployments.Core.Definitions.DeploymentParameterDefinition'. Path 'properties.parameters.aadAppClientId', line 1, position 3838.'."
In ARM, it's string type but string value is not accepting for this

**Comment by bachuv** [comment]
Hi @Nishanth123456789ab, can you please share more details about how the issue you described is shown/related to Durable Functions Monitor? Thanks!

**Comment by scale-tone** [comment]
No answer from the originator, so closing this.
If anything else needed, feel free to open another issue.
