### ISSUE TITLE
Load failed. One or more errors occurred. (This request is not authorized to perform this operation.)

### ISSUE THREAD

**Issue by bhakat1988** [microsoft/DurableFunctionsMonitor#123]
Type: <b>Bug</b>

Load failed. One or more errors occurred. (This request is not authorized to perform this operation.)
which was working day before yesterday , i have seen this error on the first day of configuring.
In the stored connection strings, Its showing request failed with status code 403

Extension version: 6.3.0
VS Code version: Code 1.80.0 (660393deaaa6d1996740ff4880f1bad43768c814, 2023-07-04T15:06:02.407Z)
OS version: Windows_NT x64 10.0.19044
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 PRO 3500U w/ Radeon Vega Mobile Gfx (8 x 2096)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|13.89GB (1.47GB free)|
|Process Argv|--crash-reporter-id c1f77ac9-74ab-45a5-8e2d-65331bed979d|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30784847
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
a9j8j154:30646983
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
a2ce3375:30757347
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
showindicator:30785052
pythongtdpath:30769146
i26e3531:30780429
pythonnosm12tcf:30779713
pythonidxpt:30784022
pythonnocebcf:30776496
h7j2d465:30786200

```

</details>

**Comment by scale-tone** [comment]
Hello @bhakat1988 , the typical cause of this error is that your Storage account has a firewall enabled, and your current IP-address is not whitelisted there. 

You need to check your Storage firewall settings and add your IP-address, if it's not there yet:
![image](https://github.com/microsoft/DurableFunctionsMonitor/assets/5447190/f1d7fb7b-f594-48ec-86cc-8e05c0a0bef7)

**Comment by scale-tone** [comment]
@bhakat1988 , do you still need more help on this?

**Comment by scale-tone** [comment]
Let's hope it helped. Feel free to open another issue, if needed.
