### ISSUE TITLE
Support Lazy Loading Large Message Inputs/Outputs

### ISSUE THREAD

**Issue by swettstein** [microsoft/DurableFunctionsMonitor#124]
When loading orchestrations and many of them have large inputs/outputs, it is helpful for performance to disable the setting FetchLargeMessagesAutomatically but this leaves the input/output value as a link to the blob. Our organization has public access to blobs disabled for security. Therefore, clicking on this link will not allow us to easily inspect the contents of this blob. It would be helpful to have a function to fetch the contents of the blob when clicking on a large input/output from the main table.

e.g.  When clicking on the following input:
![image](https://github.com/microsoft/DurableFunctionsMonitor/assets/16578892/9216d15d-0ee6-481c-b0a8-5b25bf5205da)

The modal popup currently shows:
![image](https://github.com/microsoft/DurableFunctionsMonitor/assets/16578892/068241a8-0a55-4ca7-b1b9-d73601546110)

But would like it to show the actual downloaded and decompressed json.

**Comment by scale-tone** [comment]
Indeed, sounds like a useful feature, @swettstein .
But how would you estimate the size of your inputs/outputs?

**Comment by swettstein** [comment]
some of our processes are data-heavy so they could be up to 1MB (compressed)

**Comment by scale-tone** [comment]
> some of our processes are data-heavy so they could be up to 1MB (compressed)

Wow. And would you expect that huge JSON to be just shown on the screen?
I'm asking because I really doubt it would be any helpful. I mean, how would you navigate through it?..

As an alternative, it could be a link that allows to download it as a file. Would it be more useful?

**Comment by swettstein** [comment]
> Wow. And would you expect that huge JSON to be just shown on the screen? I'm asking because I really doubt it would be any helpful. I mean, how would you navigate through it?..
> 
> As an alternative, it could be a link that allows to download it as a file. Would it be more useful?

for troubleshooting purposes, yes, it would be helpful. it wouldn't have to be shown on the screen but perhaps an on-demand button or link to download the decompressed file would work too. i would just want it to handle the auth and decompression for a seamless user experience.

to take a step back on how i got here. i was trying to load a set of Orchestrations but it was timing out. i thought that was odd given i was filtering by name and this particular Orchestration has no inputs or outputs. i dug deeper and found that the name filter can only be applied post-ListInstancesAsync which meant it was loading all Orchestrations and some of them had very large inputs that it was trying to download and decompress (even though they would eventually get filtered out). that's when i discovered FetchLargeMessagesAutomatically and setting that to False greatly improved performance. in certain cases, i do want to see the inputs (especially during development and functional testing) but all i get is a link.

**Comment by scale-tone** [comment]
OK, implemented it and published as [DurableFunctionsMonitor.DotNetBackend/6.4.0-beta3](https://www.nuget.org/packages/DurableFunctionsMonitor.DotNetBackend/6.4.0-beta3).

Large inputs/outputs should now appear in form of links:

![image](https://github.com/microsoft/DurableFunctionsMonitor/assets/5447190/0cd4f820-3df5-4cc6-9568-c228947258cc)

Clicking on a link should trigger a file download, the downloaded file should contain the full field value.

For this to work, `FetchLargeMessagesAutomatically` setting should be set to `false` in your `host.json` file.
DfMon Standalone already has that setting set in its `host.json`, but you can always override it with `AzureFunctionsJobHost__extensions__durableTask__storageProvider__FetchLargeMessagesAutomatically` config setting, if you wish to opt out of this behavior.

@swettstein , can I please ask to test it and see if it works well for you?

**Comment by swettstein** [comment]
@scale-tone sure, can do this week. thanks for implementing!

**Comment by swettstein** [comment]
functionally, it works exactly as i would expect it to.

only thing i would suggest would be better naming if it's not too much trouble. all inputs download as `input.txt` and all outputs download as `output.txt` so when downloading multiples, it may be difficult to easily see the difference. could you retain the original filename (without `.gz`)? that would also open the file in my default app for json rather than txt.
![image](https://github.com/microsoft/DurableFunctionsMonitor/assets/16578892/77ff8685-6769-4e7a-8066-bc4025701822)

**Comment by scale-tone** [comment]
Thanks for your feedback!

> it may be difficult to easily see the difference. could you retain the original filename (without .gz)?

This certainly makes sense, will do before GA.

> that would also open the file in my default app for json rather than txt

What type are your values of? 
You're getting it as `.txt` because [they look neither as objects (JSON) nor as binary data (base64)](https://github.com/microsoft/DurableFunctionsMonitor/blob/932d73e5fb80456ec20a395d619924e051c45d6b/durablefunctionsmonitor.dotnetbackend/Functions/Orchestration.cs#L413). So my assumption is they are strings, but please confirm.

**Comment by swettstein** [comment]
> What type are your values of?
> You're getting it as `.txt` because [they look neither as objects (JSON) nor as binary data (base64)](https://github.com/microsoft/DurableFunctionsMonitor/blob/932d73e5fb80456ec20a395d619924e051c45d6b/durablefunctionsmonitor.dotnetbackend/Functions/Orchestration.cs#L413). So my assumption is they are strings, but please confirm.

it appears that the content is a json array (first character is `[`) so seems json fragments are valid here. in my code, the return value of that particular function is an IEnumerable so i guess that makes sense. same for the input (parameter is an IEnumerable).

is there a way to control the serialization of inputs/outputs on durable functions? i have not seen anywhere (but i have not looked very hard). i just assumed it was always json. in what case would it be binary data?

**Comment by scale-tone** [comment]
> it appears that the content is a json array (first character is [)

Right, so it's one extra character I forgot to check. Will do.

>  in what case would it be binary data?

In my experiments it was a byte array (a PNG image) returned from my orch method.

> is there a way to control the serialization of inputs/outputs on durable functions? 

I don't know, as I'm not too close to the dev team. But we have @bachuv with us, maybe she can help.

**Comment by swettstein** [comment]
looks like it's always JSON but you can tweak the serializer settings: https://learn.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-serialization-and-persistence

i think what you have (adding the check for json array start) will be sufficient. most oversized inputs/outputs will be serialized to a json object, json array, byte array. it's possible - but unlikely - that a simple string would be oversized but the txt fallback would cover that anyway.

**Comment by scale-tone** [comment]
Done in [v6.4](https://github.com/microsoft/DurableFunctionsMonitor/releases/tag/v6.4). Pls, validate.
