### ISSUE TITLE
[Feature Request] Allow to click on pending/running sub orchestrations

### ISSUE THREAD

**Issue by junalmeida** [microsoft/DurableFunctionsMonitor#132]
When a sub orchestration is created, probably still in pending or running state, it is not possible to click on it to see the details like we can do on orchestrations that have already finished.

![image](https://github.com/microsoft/DurableFunctionsMonitor/assets/991675/bc42f1d4-c999-467c-a25d-5bb9885b274e)

It would be good to be able to click and see the sub orchestration instance.

**Comment by scale-tone** [comment]
It would be good indeed, @junalmeida !
Working on it...

**Comment by scale-tone** [comment]
Done in [v6.4](https://github.com/microsoft/DurableFunctionsMonitor/releases/tag/v6.4). Pls, validate.
