### ISSUE TITLE
[FeatureRequest] Persist column selections and sorting on instance list

### ISSUE THREAD

**Issue by junalmeida** [microsoft/DurableFunctionsMonitor#134]
When checking out the instance list, we can remove/hide some columns and sort. It would be good to persist those selections for the next time the list is open.

![image](https://github.com/microsoft/DurableFunctionsMonitor/assets/991675/6b368d8f-e3bb-4050-b88f-ae0abcc2f533)

**Comment by scale-tone** [comment]
Done in [v6.4](https://github.com/microsoft/DurableFunctionsMonitor/releases/tag/v6.4). Pls, validate.
