### ISSUE TITLE
Authentication issues

### ISSUE THREAD

**Issue by mmajcica** [microsoft/DurableFunctionsMonitor#137]
I followed the documentation to the letter and used your template do deploy the dfm in my rg.

I am facing an issue with authentication and can't understand what is happening.

![image](https://github.com/microsoft/DurableFunctionsMonitor/assets/3026551/cd7e647f-8b95-4f35-b88c-e99acada71d9)

Following is what I do see, I'm not sure if this is a 401 for what concerns my user auth or something else.

I have created the app registration as suggested and made sure the right client id is passed to the template.

This is what I do get to see in detail
![image](https://github.com/microsoft/DurableFunctionsMonitor/assets/3026551/20d92b9f-5804-461f-88ed-a80a893985cd)

Any ideas on what can be wrongly setup?

Thanks

**Comment by scale-tone** [comment]
Hi @mmajcica, what is happening is that the given user is not allowed to access your DfMon endpoint. DfMon's Function App's logs should give more details.

<img width="200px" src="https://github.com/microsoft/DurableFunctionsMonitor/assets/5447190/7655c987-f0f5-4ea8-a39f-0c38fd079455"/>

Can you check them?

Also can you confirm that the user visible on your screenshot is the correct user (is a part of your AAD tenant) and that it is either added to `DFM_ALLOWED_USER_NAMES` setting or that setting is left empty ?

**Comment by mmajcica** [comment]
It is working as expected. Seems there were some delays in applying settings in Azure. However, thank you for your time.
