### ISSUE TITLE
Entity with DateTimeOffset property is deserialized into local time zone, but claims Zulu.

### ISSUE THREAD

**Issue by marked23** [microsoft/DurableFunctionsMonitor#140]
I'm using DFM 6.3.1 and Azurite.  
My isolated durable function project is running locally in VS 2022 debugger. 

I have a DateTimeOffset property in a Durable Entity.

```csharp
public DateTimeOffset? LastRunStartDate { get; set; }
```

I have a reset method to set the date explicitly:
```csharp
public Task Reset()
{
    LastRunStartDate = DateTimeOffset.Parse("2023-04-01 12:00:00 AM +00:00");
    return Task.CompletedTask;
}
```

After setting the date, I check the table in Azure Storage Explorer.  Looks correct.
![image](https://github.com/microsoft/DurableFunctionsMonitor/assets/732793/dcc56256-3028-4cf4-a90e-9f0d848693ad)

Then I check the display in DFM.  The date has been changed to the equivalent moment in my time zone.  However the "Z" indicates that this is still UTC.     
![image](https://github.com/microsoft/DurableFunctionsMonitor/assets/732793/1528754b-f312-4b20-b5a1-ada51fe4e91b)

I expected the date to be displayed as it was stored.

**Comment by scale-tone** [comment]
Thanks for reporting this, and [here is the offending line](https://github.com/microsoft/DurableFunctionsMonitor/blob/f1757279af7f3ee35321eb28f1f5931f3fd8bc5c/durablefunctionsmonitor.dotnetbackend/Common/DetailedOrchestrationStatus.cs#L144).

Looking into what can be done to fix it...

**Comment by scale-tone** [comment]
Done in [v6.4](https://github.com/microsoft/DurableFunctionsMonitor/releases/tag/v6.4). Pls, validate.
