### ISSUE TITLE
Not able to see the monitor using the DurableFunctionsMonitor.DotNetIsolated package

### ISSUE THREAD

**Issue by pilarodriguez** [microsoft/DurableFunctionsMonitor#142]
I'm using the DurableFunctionsMonitor.DotNetIsolated 6.3.0-beta1 package and I can't start it. 
I've disabled authentication (just to test it, I will add authentication once it is working) like this:
```
var host = new HostBuilder()
    .ConfigureFunctionsWorkerDefaults((hostBuilderContext, workerAppBuilder) => {

        workerAppBuilder.UseDurableFunctionsMonitor((settings, extensionPoints) =>
        {
            // Override DfMon's settings here
            settings.DisableAuthentication = true;
            // Configure Durable Functions Monitor settings here
            
            // ....
        });
    })
    .Build();

host.Run();
```
Locally, I try to access the monitor going to this url `http://localhost:7071/api/durable-functions-monitor` and I get the following error:
```
Function 'DfmServeStaticsFunction', Invocation id 'bcd4989f-ad97-4eb4-8ebc-bb90697a5685': An exception was thrown by the invocation.
[2023-12-04T11:12:38.866Z] Result: Function 'DfmServeStaticsFunction', Invocation id 'bcd4989f-ad97-4eb4-8ebc-bb90697a5685': An exception was thrown by the invocation.
Exception: Microsoft.Azure.Functions.Worker.FunctionInputConverterException: Error converting 3 input parameters for Function 'DfmServeStaticsFunction': Could not populate the value for 'p1' parameter. Consider updating the parameter with a default value.
[2023-12-04T11:12:38.867Z] Could not populate the value for 'p2' parameter. Consider updating the parameter with a default value.
[2023-12-04T11:12:38.868Z] Could not populate the value for 'p3' parameter. Consider updating the parameter with a default value.
```
The same if I deploy it and use the function url.
I've installed the package in the same function app I already have working. Is this an issue? Do I need to create a separate function app for the monitor or am I missing something else?
If I deploy it in standalone mode, it works fine

**Comment by scale-tone** [comment]
Yes, @pilarodriguez , this seems to be an issue with `Microsoft.Azure.Functions.Worker` package version `1.20.0`.
The workaround is to downgrade it to version `1.19.0` in your project file.

**Comment by pilarodriguez** [comment]
Thank you. Is there a plan to fix that problem soon?

**Comment by scale-tone** [comment]
Should now work fine in the release version: [v6.4](https://github.com/microsoft/DurableFunctionsMonitor/releases/tag/v6.4). Pls, validate.
