### ISSUE TITLE
Does this work with Durable Azure Python Functions?

### ISSUE THREAD

**Issue by SeaDude** [microsoft/DurableFunctionsMonitor#146]
Or is this only useful with C# functions?

Thank you!

**Comment by scale-tone** [comment]
@SeaDude , this works with [all supported programming languages](https://learn.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-overview?tabs=in-process%2Cnodejs-v3%2Cv1-model&pivots=csharp#language-support).

**Comment by SeaDude** [comment]
Thank you!
