### ISSUE TITLE
Running as a Docker container: Unable to set CLIENT_ID and OPENID_ISSUER

### ISSUE THREAD

**Issue by jaliyaudagedara** [microsoft/DurableFunctionsMonitor#151]
I tried to DFM in an Azure Web App for Containers.
![image](https://github.com/microsoft/DurableFunctionsMonitor/assets/5653381/d2598a66-d683-4ed6-8531-4bde30f4f5b0)

I can access the DFM without authentication, but I cannot enable authentication by [setting the necessary configuration](https://github.com/microsoft/DurableFunctionsMonitor/wiki/How-to-configure-authentication).
```
WEBSITE_AUTH_CLIENT_ID to the newly created app registration's Client Id;
WEBSITE_AUTH_OPENID_ISSUER to https://login.microsoftonline.com/<my-azure-tenant-id>/v2.0.
```
![image](https://github.com/microsoft/DurableFunctionsMonitor/assets/5653381/e6f9cb37-bffd-4e02-9378-662576f03ffe)

**Comment by scale-tone** [comment]
Running DfMon "in an Azure Web App for Containers" is not supported and is not going to be supported.
DfMon is an Azure Function, and cannot be run as a Web App.

All supported ways of running DfMon [are described here](https://github.com/microsoft/DurableFunctionsMonitor/wiki/How-to-run-DfMon-in-Standalone-mode).

**Comment by jaliyaudagedara** [comment]
@scale-tone,

Oh yes, I am so sorry, it's my mistake.

Thanks!
