### ISSUE TITLE
dotnet 8 support in isolated mode

### ISSUE THREAD

**Issue by lkurzyniec** [microsoft/DurableFunctionsMonitor#163]
> The selected version '.NET 7 Isolated' will deprecate on 5/14/2024. Please consider updating it soon.[Learn more](https://go.microsoft.com/fwlink/?linkid=2202628)

**Comment by scale-tone** [comment]
Thanks for the remainder, @lkurzyniec , will certainly take care of this.

**Comment by mronnblom-ith** [comment]
Seriously? This needs to be high prio! .Net 7 is a Maintenance release that many cannot use.

**Comment by scale-tone** [comment]
Hello @mronnblom-ith , to clarify: .NET versions are backward-compatible. 
So nothing prevents you to inject the current DfMon Isolated package into your .NET 8 projects (in which case it is .NET 8 that will be actually used, of course).

**Comment by mronnblom-ith** [comment]
Ok, that is reasonable. It is probably the AspNet Core integration incompatibility that is causing my problems then, not the .Net version.

**Comment by lkurzyniec** [comment]
I'm using standalone isolated version, and it's not working with `.NET 8 Isolated` .NET version of Function App.

**Comment by scale-tone** [comment]
@lkurzyniec , can you please provide more details? How exactly is it not working?

**Comment by lkurzyniec** [comment]
I have a working version on `.NET 7 Isolated`.
![image](https://github.com/microsoft/DurableFunctionsMonitor/assets/5943484/df5a8036-85ce-4da1-9099-7fb6dd8e979c)

When I changed to `.NET 8 Isolated`, it stops working.
![image](https://github.com/microsoft/DurableFunctionsMonitor/assets/5943484/be7abd22-097c-431b-a02b-5057fa65fc71)

![image](https://github.com/microsoft/DurableFunctionsMonitor/assets/5943484/0e010606-d494-4ab9-987b-da306ea07492)
> Error details
> Encountered an error (InternalServerError) from host runtime.

**Comment by scale-tone** [comment]
@lkurzyniec , I confirm there seems to be an issue like that on a **Linux** platform. When deploying an empty .NET Isolated project targeting .NET 7 and then changing .NET version to 8 in the instance's settings, the app fails to work until you change TargetFramework to `net8.0` in CSPROJ file and redeploy.

On a Windows instance (the one which you'd get by [deploying the included ARM template](https://github.com/microsoft/DurableFunctionsMonitor/tree/main/durablefunctionsmonitor.dotnetisolated#how-to-deploy-to-azure)) this does not happen though - DfMon Isolated works fine.

**Comment by lkurzyniec** [comment]
When creating it from scratch in `.NET 8 Isolated`, the problem is the same.
![image](https://github.com/microsoft/DurableFunctionsMonitor/assets/5943484/aa9272d2-d400-440b-aa79-215fd4c01047)

**Comment by scale-tone** [comment]
Anyway, [this 6.5.0-beta2](https://www.nuget.org/packages/DurableFunctionsMonitor.DotNetIsolated/6.5.0-beta2) package should work (as it targets .NET 8).

Can you please check?

**Comment by lkurzyniec** [comment]
It's working 🚀 
Now I can wait for a stable release of the package, and then I will close that issue.
Thx for that 💪🏼

**Comment by lkurzyniec** [comment]
It would be nice to bump `Azure.Identity` as version [1.10.4](https://www.nuget.org/packages/Azure.Identity/1.10.4) is vulnerable.

**Comment by lkurzyniec** [comment]
@scale-tone here is PR: https://github.com/microsoft/DurableFunctionsMonitor/pull/179

**Comment by scale-tone** [comment]
Thanks a lot for your PR, @lkurzyniec !

Typical trouble with massive package bump-ups is that it often breaks things, sometimes in very unexpected places. E.g. [here is an example of Microsoft.IdentityModel.Protocols.OpenIdConnect](https://github.com/microsoft/DurableFunctionsMonitor/issues/136).

And sadly here in DfMon, with all its incarnations, all these numerous ways of running it, all various platforms and pricing tiers, we do not have a 100% reliable auto-tests. So I will have to manually and gradually apply your changes, to check that nothing gets broken. Please, give me some time for that...

**Comment by lkurzyniec** [comment]
Got it. I didn't think that upgrading the version could be so risky and painful. I thought it is a matter of building the projects.

**Comment by lkurzyniec** [comment]
@scale-tone any ETA for a new stable version?

**Comment by scale-tone** [comment]
[Done](https://github.com/microsoft/DurableFunctionsMonitor/releases/tag/v6.5)
