### ISSUE TITLE
[Feature Request] PWA start page

### ISSUE THREAD

**Issue by pschaeflein** [microsoft/DurableFunctionsMonitor#164]
When running DFM as standalone from Azure functions, Edge/Chrome allows for "Installing this site as an app". This includes the favicon.

However, the app launches to /index.html. That page renders a plain page with the message "Task Hub name is invalid".

Can you update the PWA manifest so that launching provides the same selection experience as navigating to the function url without the index.html specified (e.g. "[functionname].azurewebsites.net")?  

Or provide instructions how to modify my instance/fork.

Thanks.

**Comment by scale-tone** [comment]
That's a great suggestion, @pschaeflein , thanks!
Expect this to happen in the next release (no commitments though, sorry).

**Comment by scale-tone** [comment]
Done in [v6.4](https://github.com/microsoft/DurableFunctionsMonitor/releases/tag/v6.4). Pls, validate.
