### ISSUE TITLE
About Function - how to invoke with defaults

### ISSUE THREAD

**Issue by lkurzyniec** [microsoft/DurableFunctionsMonitor#171]
I'm using an isolated standalone version with rather default options (with storage connection string, as described [here](https://github.com/microsoft/DurableFunctionsMonitor/blob/main/durablefunctionsmonitor.dotnetisolated/arm-template.json)).
In such case, how to invoke About endpoint ([About.cs](https://github.com/microsoft/DurableFunctionsMonitor/blob/main/durablefunctionsmonitor.dotnetisolated.core/Functions/About.cs))?

**Comment by scale-tone** [comment]
Hi @lkurzyniec , not sure I fully understand your question.

Are you asking about what the URL of that endpoint would be (in which case it is `https://my-isolated-dfmon.azurewebsites.net/durable-functions-monitor/a/p/i/--MyTaskHubName/about`)?

Or are you interested to know about authentication-related things, or anything else?

May I also ask you to elaborate on what you're ultimately trying to achieve?

**Comment by lkurzyniec** [comment]
I'm using isolated and standalone version. I'm deploying it with Terraform, and I reflected [this](https://github.com/microsoft/DurableFunctionsMonitor/blob/main/durablefunctionsmonitor.dotnetisolated/arm-template.json) template. I couldn't reach About endpoint, I was getting 404. With your url/example (`https://my-isolated-dfmon.azurewebsites.net/durable-functions-monitor/a/p/i/--MyTaskHubName/about`) I solved my problem. I thought in standalone version I can skip `durable-functions-monitor` url part, but I can't. This line confused me: https://github.com/microsoft/DurableFunctionsMonitor/blob/main/durablefunctionsmonitor.dotnetisolated.core/Functions/About.cs#L16
