### ISSUE TITLE
Troubleshooting disappearing Storage Account and TaskHub instance

### ISSUE THREAD

**Issue by xsurfer** [microsoft/DurableFunctionsMonitor#175]
Recently, one of the Storage Accounts and its associated TaskHub instance disappeared from the list of available ones. I do have proper access to the Storage Account.

However, I am able to connect to the TaskHub by using the ConnectionString and TaskHub name.
Unfortunately, I am unable to delete the TaskHub using this method, and it's something I would like to do.

I have already attempted reinstalling the latest extension (version 6.4.0), and I have also tried downgrading it to version 6.3.0, but it didn't resolve the issue.

Here is the link to an image for reference: 
![image](https://github.com/microsoft/DurableFunctionsMonitor/assets/895121/71e62309-cd53-488b-8f8d-eb81c88ef3c3)

Do you have any suggestions on how to troubleshoot this further?

Thank you!

**Comment by scale-tone** [comment]
Hi @xsurfer , DfMon-as-VsCode's default algorithm of discovering Task Hubs is as follows:

It tries to 'list keys' of all Storage accounts accessible by you. If successful, it then continues to use those Storage keys for interacting those Storage accounts.

If for whatever reason it is unable to get Storage keys, it falls back to using (your) identity-based access.

To explicitly control which method to use there's this setting:
![image](https://github.com/microsoft/DurableFunctionsMonitor/assets/5447190/8d1996e6-0ada-4250-ac03-d45e7d64e1c4)

If you say that a Storage account suddenly "disappeared" from DfMon's list, then I suggest you check if someone (or something) has changed access policies and other settings of that Storage account. A typical change being made is prohibiting Storage keys to be used (note that it might take a while to see the effect of that on your existing connection strings).

You can also play with the above "Task Hubs Discovery Mode" setting, to see if different modes produce different results. Just make sure you restart VsCode after changing it.

**Comment by xsurfer** [comment]
hi @scale-tone, thank you for your reply.

> You can also play with the above "Task Hubs Discovery Mode" setting, to see if different modes produce different results. Just make sure you restart VsCode after changing it.

I did but unfortunately it didn't help :( 

> If you say that a Storage account suddenly "disappeared" from DfMon's list, then I suggest you check if someone (or something) has changed access policies and other settings of that Storage account. A typical change being made is prohibiting Storage keys to be used (note that it might take a while to see the effect of that on your existing connection strings).

I do have same RBAC assignment as for other Storage Accounts that are visible in the extension.

I also checked storage key setting and it is enabled.

![image](https://github.com/microsoft/DurableFunctionsMonitor/assets/895121/840a0140-181f-45e8-9fa3-fb431f98d779)

Do you have any other reco/idea on what to check?

What is the monitor exactly looking for within the storage account (on top of instance and history tables, and work item and control queues)? Maybe someone could have deleted a relevant item by mistake (some colleague of mine delete tables and queues manually so that TaskHub is recreated from scratch when Func App restarts).

Do you think this may be related to the fact that I've recently upgraded Durable Task library to v3 which is in preview mode?

Thank you!

**Comment by scale-tone** [comment]
> it is looking for Instances and History tables and then extracting TaskHub name from the full table name

Yes, and the only next thing I can suggest is to manually look for those tables. You can use Azure portal or Azure Storage Explorer for that. 

> Do you think this may be related to the fact that I've recently upgraded Durable Task library to v3 which is in preview mode?

I don't know, and would appreciate if you check that hypothesis (whether they've out of a sudden changed table name format).

**Comment by scale-tone** [comment]
Do you still need help on this, @xsurfer ?

**Comment by xsurfer** [comment]
@scale-tone if you would be able to help me further, I'd really appreciate that!

Both tables, Instances and History, are in place (they are not renamed/deleted in the Durable Task v3) along with a new one, Partitions, added in the Durable Task v3.

![image](https://github.com/microsoft/DurableFunctionsMonitor/assets/895121/41732106-f725-4d60-87f0-682c8c3d69d4)

Said that, everything seems in order, still I'm not able to list the hub stored in one of my Storage Account

**Comment by scale-tone** [comment]
@xsurfer , can you tell me how many tables you have there in this storage account in total?

**Comment by mkraghavan** [comment]
I am aslo facing the same issue. Were you able to find a solution to resolve this?

**Comment by mkraghavan** [comment]
![image](https://github.com/microsoft/DurableFunctionsMonitor/assets/121021194/1cc405cb-d1f1-425c-a8aa-dfedfa3167cc)
I have these 2

**Comment by mkraghavan** [comment]
I also see that the taskhubname is appearing as null:

![image](https://github.com/microsoft/DurableFunctionsMonitor/assets/121021194/ae019f46-bc99-4cd4-8587-95886cd94099)

**Comment by scale-tone** [comment]
@mkraghavan , are you saying you have those two (and only two) tables in your storage account and you do not see *any* Task Hubs in DfMon VsCode?
Do you see any Task Hubs in any other storage account in DfMon VsCode?
Were you able to see those Task Hubs there before?

Are you sure you're signed in into Azure in your VsCode? Occasionaly you need to re-login, also just recently they seem to roll out a change in VsCode, which caused re-logins be required more frequently. 

Can you see any other Azure resources on your AZURE tab in VsCode? Again, due to that potential recent change in VsCode it might take several VsCode *restarts* and login interactions to make you see your Azure resources there again.

Does DfMon's Output Channel show any errors to you?

That screen with "TaskHubName" column being null - where does it come from (cause it is definitely not a part of DfMon)?

**Comment by mkraghavan** [comment]
@scale-tone 
_are you saying you have those two (and only two) tables in your storage account and you do not see any Task Hubs in DfMon VsCode?_   No, now when i checked Azure storage explorer I see these also:
![image](https://github.com/microsoft/DurableFunctionsMonitor/assets/121021194/817ecd9a-942e-4fd2-a8a5-cb5bf6ac9336)


_Do you see any Task Hubs in any other storage account in DfMon VsCode?_ Yes, I have a lot of other storage accounts withTaskhubs and I can see the task hubs in there

_Are you sure you're signed in into Azure in your VsCode?_  All the other storage accounts have the same permissions as this one and I can see all the others. I manually added the storage account in dfmon and it shows something like this:
![image](https://github.com/microsoft/DurableFunctionsMonitor/assets/121021194/34a0770c-5aa9-42bd-8645-7af0db10dd08)

_Can you see any other Azure resources on your AZURE tab in VsCode?_  Yes, I can

_Does DfMon's Output Channel show any errors to you?_ No

_That screen with "TaskHubName" column being null - where does it come from (cause it is definitely not a part of DfMon)?_ 
That is from the azure storage explorer - Instances table:
![image](https://github.com/microsoft/DurableFunctionsMonitor/assets/121021194/8f5d960b-9acf-4b5a-a223-33d31b13103c)

**Comment by mkraghavan** [comment]
That actually did resolve it for me! Thanks a lot!

**Comment by xsurfer** [comment]
I can also confirm the fix resolved the issue for me as well. @scale-tone thank you so much!
