### ISSUE TITLE
SQL MI Connection

### ISSUE THREAD

**Issue by saranb92** [microsoft/DurableFunctionsMonitor#177]
while using User name Password connective via service account getting error DFM_ALTERNATIVE_CONNECTION_STRING-user-id not provided. please expline the environment field name DFM_ALTERNATIVE_CONNECTION_STRING usage while connecting to SQL MI for the Monitoring.
```[tasklist]
### Tasks
```

**Comment by scale-tone** [comment]
Hello @saranb92 ,

As documented:

  <img width="500px" src="https://github.com/microsoft/DurableFunctionsMonitor/assets/5447190/3ac59904-6e25-47dd-8530-b40aa090981b" />

, to monitor Task Hubs managed by Durable Task SQL Provider you need to use [DfMon for Durable Task SQL Provider](https://github.com/microsoft/DurableFunctionsMonitor/tree/main/custom-backends/mssql#durable-functions-monitor-for-mssql-storage-provider). See detailed instructions there on how to configure it.

DFM_ALTERNATIVE_CONNECTION_STRING_XXX settings are only intended and only supported for the default, Azure Storage-based durability provider. Don't use them with MSSQL storage.

An alternative (and the easiest) way of monitoring all supported durability providers (Azure Storage, MSSQL and Netherite) is to use [DfMon-as-a-VsCode-Extension](https://marketplace.visualstudio.com/items?itemName=DurableFunctionsMonitor.durablefunctionsmonitor).
