### ISSUE TITLE
Azure Account extension that Durable Functions Monitor extension depends on for authentication will be deprecated in January 2025

### ISSUE THREAD

**Issue by alexweininger** [microsoft/DurableFunctionsMonitor#178]
Hello 👋,

**Azure Account extension that the Durable Functions Monitor extension depends on for authentication will be deprecated in January 2025.** Please see https://github.com/microsoft/vscode-azure-account/issues/964 for more details.

Please reach out to me on Teams for questions or support.

**Comment by scale-tone** [comment]
Fixed in [v6.5.1](https://github.com/microsoft/DurableFunctionsMonitor/releases/tag/v6.5.1)
