### ISSUE TITLE
DfMon not an official Microsoft product

### ISSUE THREAD

**Issue by mronnblom-ith** [microsoft/DurableFunctionsMonitor#181]
Hi! I just now realized that DfMon is not an official Microsoft product! I was convinced it was. So sorry @scale-tone for somewhat unreasonable demands! 
What I find weird and a bit disturbing though, is that Microsoft (to my knowledge) does not have any product what-so-ever for monitoring och administering Durable Functions. They even link to DfMon from their official docs! And it's listed here on GitHub under the Microsoft "account". So from the customer's (developer's) perspective, it _does_ feel reasonable to have some demands on being able to monitor and administer Durable Functions, but those demands cannot of course be directed at DfMon's maintainers. What I am thinking about is if we can petition Microsoft to adopt DfMon, but I have no idea what the current maintainers of it think about that, or how you would go about doing so. Would be interesting to hear your thoughts.

**Comment by bachuv** [comment]
Hi @mronnblom-ith, Durable Functions Monitor is an official Microsoft product.

**Comment by mronnblom-ith** [comment]
@bachuv This is a screen shot of the README in this same repo:

![image](https://github.com/microsoft/DurableFunctionsMonitor/assets/55319429/60d2266c-40eb-43da-82f5-6c5c4ce89e81)

**Comment by davidmrdavid** [comment]
@mronnblom-ith: Ah, good catch. The project originally started as a third party contribution to Durable Functions (although the author was at Microsoft) but since then the project has migrated to be co-owned by the Durable Functions team, making it "official". I'll look to remove that confusing bit of the README, thank you for pointing it out.

**Comment by davidmrdavid** [comment]
Please do note that observability is an area we're actively investing in, both through efforts like [Distributed Tracing](https://techcommunity.microsoft.com/t5/apps-on-azure-blog/preview-of-distributed-tracing-v2-for-durable-functions/ba-p/4039050), the recent co-ownership of the Durable Functions Monitor, as well as other efforts that are yet to be announced. 

You're definitely encouraged to make feature requests and report bugs in this repo, as it is part of our (the Durable Functions team's) weekly triage of issues. Just please note that this is just one of several components we maintain, and as such we sometimes can't prioritize it all.
