### ISSUE TITLE
Should username claim be case insensitive?

### ISSUE THREAD

**Issue by vineetnair** [microsoft/DurableFunctionsMonitor#20]
Great work with this project guys! So useful :)

I noticed the username-based claim failed a couple of times for us due to case-sensitivity reasons. Should this check be done case-insensitively?

**Comment by scale-tone** [comment]
Thanks for your feedback, @vineetnair .

Are you saying that the same username sometimes appears in e.g. lower case and sometimes in upper case in your tokens?

**Comment by vineetnair** [comment]
No, the username claim via the token just retains the casing in which it was setup in AAD. But the configuration in DFM to only allow certain users seems to have a case-sensitive checking.

So, if the claim is John.Smith@contoso.com and the allowed username is john.smith@contoso.com, it doesn't allow access and throws a 401.

**Comment by vineetnair** [comment]
That's fair, thanks
