### ISSUE TITLE
VS Code extension detects latest Azure Functions Core Tools detected as v4.0.1

### ISSUE THREAD

**Issue by HolisticDeveloper** [microsoft/DurableFunctionsMonitor#207]
I've recently moved to a new computer and I'm trying to set up Durable Functions Monitor in VS Code again. After installing Azure Function Core Tools globally via chocolatey (`choco install azure-functions-core-tools`), I get the following error when trying to attach to a task hub:

> Default backend now requires at least Azure Functions Core Tools v4.0.4629 (currently discovered is v4.0.1). Install latest Azure Functions Core Tools or, alternatively, select a custom backend in extension's settings.

The package version installed by chocolatey is 4.0.5907, and I get the following output from `func.exe`:
```
Core Tools Version:       4.0.1 Commit hash: N/A +807e89766a92b14fd07b9f0bc2bea1d8777ab209 (32-bit)
Function Runtime Version: 4.834.3.22875
```

Have I misconfigured something?

**Comment by scale-tone** [comment]
@HolisticDeveloper , can you post the output from your 'DURABLE FUNCTIONS MONITOR' output channel, when trying to attach?

**Comment by scale-tone** [comment]
@HolisticDeveloper , do you still need help on this?

**Comment by HolisticDeveloper** [comment]
Sorry for the delay, I got sidetracked by a pressing issue...

Here's the output:

```txt
yarn global bin failed. Command failed: yarn global bin
'yarn' is not recognized as an internal or external command,
operable program or batch file.
Using Functions host: func
```

I've learned that yarn [isn't supposed to be installed globally anymore](https://yarnpkg.com/getting-started/install) but I did run `corepack enable` which made the yarn error go away. Now my output is just the last line:

```txt
Using Functions host: func
```

**Comment by scale-tone** [comment]
@HolisticDeveloper , [the logic of discovering the path to func.exe is here](https://github.com/microsoft/DurableFunctionsMonitor/blob/b4e8d7a499081146df27c6dac739770fcb6d3680/durablefunctionsmonitor-vscodeext/src/BackendProcess.ts#L425).
It is a multi-stage process, that checks all known homes of Azure Functions Core Tools (as an npm package, via yarn, as an .MSI file etc.). If you're saying that you only see that one line in the output, then I'm afraid I cannot explain it.

Anyway, you can always explicitly specify the full path to func.exe via this setting:

![image](https://github.com/user-attachments/assets/2849888e-04d9-410b-a881-dbe2a1c4da1b)

**Comment by HolisticDeveloper** [comment]
Well, even the tool itself [thinks it is old](https://github.com/Azure/azure-functions-core-tools/issues/3776). 🤷🏻‍♂️ 

Maybe there has been a change in what is reported by `func --version`. I don't have older versions around to check.

**Comment by HolisticDeveloper** [comment]
Since the extension is looking for a minimum version of `4.0.4629`, I decided to download that version and set an explicit path to it. The download links were contained in `%LocalAppData%\AzureFunctionTools\feed-v{0000000}.json` (where `0000000` varies). The output of `func --version` for this binary is `4.0.4629`.

The extension is working after doing this. Feel free to close if you don't plan to work around this issue.

**Comment by scale-tone** [comment]
Closing this one. Feel free to open more issues, if something is not right.
