### ISSUE TITLE
Problem to use app roles in combination with groups as read-only takes precedence over full access

### ISSUE THREAD

**Issue by ziegler-daniel** [microsoft/DurableFunctionsMonitor#221]
Thank you for clarifying the behavior regarding the app roles in [ReadOnly mode takes precedence over Normal/Edit Mode if a user has perms for both ](https://github.com/microsoft/DurableFunctionsMonitor/issues/213).

In my opinion, however, the DurableFunctionMonitor behaves contrary to Microsoft's RBAC in this respect. There, roles are additive and it is not the weakest role that counts (see [RBAC - Multiple role assignments](https://learn.microsoft.com/en-us/azure/role-based-access-control/overview#multiple-role-assignments)).

Let us consider the following case:
* We have two groups of users. One group should get read-only access and one full access.
* Therefore, we assign a read-only app role to the first group and a full access app role to the second group.
* If a user is now in both groups, they only have read access, although they should have full access.

In my opinion, the only solution in this case is to assign the desired role to each user individually, which is very impractical.

Is this behavior really intentional? And is there a simple solution to this problem that I have overlooked?

Thank you very much in advance.

**Comment by scale-tone** [comment]
>  role to each user individually
> is there a simple solution to this problem that I have overlooked?

Luckily, DfMon is decoupled from groups and instead operates with app roles. So in your scenario, you could assign that `full access app role` to that special user personally - and (sadly I can't validate it right now, but last time I checked) this assignment would take precedence over group-assigned roles. 
So no need to do it for every user, only for that special one.
Hope it helps, and please let me know if I'm mistaken on the above.

**Comment by ziegler-daniel** [comment]
Thank you for your response.

If I assign the `full access role` to the user individually, the user will additionally get the `read only role` from the group assignment as the app roles claim is a multi-value attribute. You can see this here: https://www.youtube.com/watch?v=S4TgYmhv40c&t=1200s

**Comment by scale-tone** [comment]
You're super-welcome to submit a PR on this (or in fact on anything else) ! :)

**Comment by scale-tone** [comment]
Thanks a lot for your contribution on this, @ziegler-daniel !
Just pushed beta packages containing your change:

- [DurableFunctionsMonitor.DotNetBackend/6.6.0-beta1](https://www.nuget.org/packages/DurableFunctionsMonitor.DotNetBackend/6.6.0-beta1)
- [DurableFunctionsMonitor.DotNetIsolated/6.6.0-beta1](https://www.nuget.org/packages/DurableFunctionsMonitor.DotNetIsolated/6.6.0-beta1)

Can I ask you to confirm that they work for you?

**Comment by ziegler-daniel** [comment]
Thank you @scale-tone for creating the beta packages.

I tested the [DurableFunctionsMonitor.DotNetBackend/6.6.0-beta1](https://www.nuget.org/packages/DurableFunctionsMonitor.DotNetBackend/6.6.0-beta1) package in our setup and it works as expected.

Unfortunately, I don't have a setup to test the [DurableFunctionsMonitor.DotNetIsolated/6.6.0-beta1](https://www.nuget.org/packages/DurableFunctionsMonitor.DotNetIsolated/6.6.0-beta1) package easily.

**Comment by scale-tone** [comment]
Pushed as part of [v6.6](https://github.com/microsoft/DurableFunctionsMonitor/releases/tag/v6.6). Thanks for your help again, @ziegler-daniel !
