### ISSUE TITLE
Migrate to Functions v4

### ISSUE THREAD

**Issue by Don-Katsu** [microsoft/DurableFunctionsMonitor#56]
Deployed DfMon instance to Azure from latest NuGet package (using handy button on "How-to-run-DfMon-in-Standalone-mode" page). I see that Azure is warning to update function application to the Functions 4.x runtime by December 3rd.

![Monitor_Support](https://user-images.githubusercontent.com/114178426/191810548-0302cb9e-bc4c-4bc9-a710-f48ea12ab872.png)

Is this something that can be easily fixed before losing the support by December 3rd?

**Comment by scale-tone** [comment]
Thanks for reporting this, @Don-Katsu , we will concentrate on upgrading to Functions 4.x.
