### ISSUE TITLE
Unable to see the subscription account in the durable section on VS code

### ISSUE THREAD

**Issue by prerna-tesser** [microsoft/DurableFunctionsMonitor#6]
I am unable to see the subscription account in the durable functions section of the Azure tab on VS code. Because of this, I am unable to view the test hubs created for monitoring the codes and debugging on the Durable Monitor. I can't open the Durable Monitor either. The VS code was reinstalled with the updated version and the Durable Functions Monitor extension was also installed. I am using a Mac device.
<img width="190" alt="Screenshot 2021-12-28 at 3 42 33 PM" src="https://user-images.githubusercontent.com/82448615/147555643-ffcc1638-c784-4580-bf85-4390e639dabf.png">

**Comment by scale-tone** [comment]
@prerna-tesser , please, check the following:

1. That your VsCode instance is properly logged in into Azure. Use the 'Azure: Sign In' command:

   ![image](https://user-images.githubusercontent.com/5447190/147559534-ef95b5dc-5eb9-4f00-bbf3-318f6f02e0bd.png)

   VsCode might occasionally get logged out, so you might need to do this login procedure again.

2. That your subscription is not filtered out. Use the 'Azure: Select Subscriptions' command:

   ![image](https://user-images.githubusercontent.com/5447190/147559837-f714b440-7b85-4f4a-a361-d697289522a4.png)

3. That there're no error messages shown. Press the bell button to explicitly check that:

   ![image](https://user-images.githubusercontent.com/5447190/147560302-72905cfc-da75-4e1b-a822-07a8d8aa3b7f.png)

   If there're errors, tell me what they are.

Alternatively, you can always directly connect to your Task Hub by executing the 'Durable Functions Monitor' command

   ![image](https://user-images.githubusercontent.com/5447190/147560072-db28131c-0ad8-41ac-a9fc-147967d217e3.png)

and entering the Storage Connection String.


Does that resolve the issue?

**Comment by prerna-tesser** [comment]
I tried the first three steps and everything was displayed as mentioned by you. However when I directly connected to my Task Hub by executing the 'Durable Functions Monitor' command, I get this error message: 

" Command 'Durable Functions Monitor' resulted in an error (command 'extension.durableFunctionsMonitor' not found)"

<img width="251" alt="Screenshot 2021-12-28 at 5 21 44 PM" src="https://user-images.githubusercontent.com/82448615/147563651-197e35bc-b481-46c7-b39e-4c23e7803ece.png">

I have checked the extension's installation and it all seems to be fine. 

Also the subscription account for the other sections seems to be opening correctly except for Durable Functions.

**Comment by scale-tone** [comment]
Then it looks very much like DfMon extension fails to be activated. And in that case VsCode should show you an error message similar to this one:
![image](https://user-images.githubusercontent.com/5447190/147566213-c844bc74-8eb7-43ad-a060-aae5466fb53a.png)

Can you try to restart VsCode, then try to activate DfMon (by e.g. executing the 'Durable Functions Monitor' command) and tell me what exactly this error message says?

(If you don't see any error messages, try to click on that Bell button)

**Comment by prerna-tesser** [comment]
It gives the same error message as the previous one. And the bell icon says no new notifications. 

Could this be an issue because I am using a Mac?

**Comment by scale-tone** [comment]
> Could this be an issue because I am using a Mac?

I'm not aware of any Mac-specific issues by far. We need to figure out what went wrong in your specific case.

Are you installing DfMon from the Marketplace or by any other means?

Can you please try to reinstall (**uninstalll, then restart VsCode, then install again**) DfMon extension and see if there're any error messages shown during this process? Once done, can you please post a screenshot of your entire VsCode window (blurring any secrets, of course)?

**Comment by prerna-tesser** [comment]
I am downloading it from the extensions tab available on VS code. 
I followed the steps as mentioned above, however no notifications are shown during the uninstall and reinstall process.
PFA the screenshot of the same. 
<img width="1272" alt="Screenshot 2021-12-30 at 9 25 52 AM" src="https://user-images.githubusercontent.com/82448615/147720549-05d98482-fd35-4716-9acf-f19b6937919c.png">

And when I close VScode and restart it to check for the DFMon, this error message pops up: 

<img width="1278" alt="Screenshot 2021-12-30 at 9 26 44 AM" src="https://user-images.githubusercontent.com/82448615/147720587-e24bb102-263b-4a2d-995f-3e4bde38f89a.png">

**Comment by scale-tone** [comment]
@prerna-tesser , I can see you have some project ('TesserAPIPYDurableFuncApps') opened.

Can you please try to close it and open some other, blank folder in your VsCode? 
Does DfMon show the same error and behaves in the same way, when you do so?

My hypothesis is that there might be some files in that 'TesserAPIPYDurableFuncApps' project that DfMon tries to parse at startup and fails.

**Comment by prerna-tesser** [comment]
Thank you it worked when I closed the project and restarted it. 
Thank you.

**Comment by scale-tone** [comment]
Great to know it eventually works.
But it would still be very interesting to learn what's so specific in this'TesserAPIPYDurableFuncApps' project that causes DfMon to fail.
Do you have a 'local.settings.json' file in it? Does that file by any chance contain any comments (`//` or '/**/') ?

**Comment by prerna-tesser** [comment]
Yes, exactly. The local.settings.json contains //

**Comment by scale-tone** [comment]
I suggest you remove those comments then (as, generally speaking, it is not a valid JSON).

But thanks for reporting this issue. Closing this one in favor of #7.
