### ISSUE TITLE
Load failed. Request failed with status 500

### ISSUE THREAD

**Issue by CryptoTradee** [microsoft/DurableFunctionsMonitor#70]
Load failed. Request failed with status code 500.

Got the auth working now but not sure what's wrong. The Manage Storage Connection Settings has my connection string in there. I'm using it as the nuget package with just plain DfmEndpoint.Setup(); call. Running on Functions v4 Windows x64.

![image](https://user-images.githubusercontent.com/45982911/201809125-a767e2b5-6ce3-4ed8-8ed0-571491f131f7.png)

**Comment by scale-tone** [comment]
@CryptoTradee , please, provide console output (aka logs) from your Function instance. There should be a clear explanation of what's going on and what the actual error is.

If you deployed your Function to Azure, then the quickest way of getting those logs is to use 'Log stream' tab:
![image](https://user-images.githubusercontent.com/5447190/201880740-4ad2cb2d-0b14-4039-9c9a-2dd42f30334c.png)

**Comment by scale-tone** [comment]
@CryptoTradee , would you be able to provide further info on this?

**Comment by CryptoTradee** [comment]
Thanks @scale-tone . Yes I had registered Autofac as my IOC for the Azure functions. The error came cause the DFM functions/services weren't registered with Autofac. I thought about checking the errors and registering them or alternatively switching my IOC to be the standard one however ended up just making a seperate azure function and then just read from my original functions storage. 

Might be something for the Azure function team but if this would be possible of some functions registered with Autofac (ie my functions) then the DFM functions are resolved with the standard implementation. Otherwise for DFM not to use any IOC?
