### ISSUE TITLE
Question: Netherite monitor in Standalone mode

### ISSUE THREAD

**Issue by Erry91** [microsoft/DurableFunctionsMonitor#93]
Hi,
I wanted to ask whether this is possible at the moment. I have a durable function monitor deployed in standalone mode that is monitoring taskhubs from an Azure storage. I then moved one function app that I was monitoring to Netherite but from the durable Monitor I can only see task hub names of functions that are using AzureStorage as storage provider. 

Is this possible at all or am I missing something from the picture?

**Comment by scale-tone** [comment]
Yes, from now on it is possible to monitor Netherite-backed Task Hubs, we've just made an update to enable that.

You can use this button:

[![Deploy to Azure](https://aka.ms/deploytoazurebutton)](https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2Fmicrosoft%2FDurableFunctionsMonitor%2Fmain%2Fcustom-backends%2Fnetherite%2Farm-template.json)

to deploy a customized Standalone DfMon instance, that monitors Netherite.

Note that DfMon instances are specific to each particular Storage Provider used. So you'll need to either reimage your existing instance or deploy a separate one, dedicated to Netherite.

**Comment by Erry91** [comment]
Thank you very much @scale-tone!
I had missed the part of having to recreate one instance to monitor a particular storage provider :)
I just tried with the link you provided and I can successfully see the new task-hubs that have been created for Netherite.

Thank you!
